baseURL = 'https://jtemporal.github.io/dev-diaries'
languageCode = 'pt'
title = 'Dev Diaries'
theme = 'hugo-book'

defaultContentLanguage = 'pt'
[languages]
  [languages.pt]
    contentDir = 'content'
    languageName = 'Português'
    weight = 10
  [languages.en]
    contentDir = 'content.en'
    languageName = 'English'
    weight = 10