baseURL = 'https://jtemporal.com/dev-diaries'
languageCode = 'pt'
title = 'Dev Diaries'
theme = 'hugo-book'

[params]
  author = 'Jessica Temporal'
  description = 'Diary of my adventure developing things'

[menu]
[[menu.after]]
  name = 'Blog'
  url = 'https://jtemporal.com/'
  weight = 10

[[menu.after]]
  name = 'GitFichas'
  url = 'https://gitfichas.com/'
  weight = 20

defaultContentLanguage = 'pt'
[languages]
  [languages.pt]
    contentDir = 'content'
    languageName = 'Português'
    weight = 10
  [languages.en]
    contentDir = 'content.en'
    languageName = 'English'
    weight = 10